### ISSUE TITLE
Multiple valid solutions in Travel Planning

### ISSUE THREAD

**Issue by shubhamprshr27** [google-deepmind/natural-plan#1]
Hi Authors,

Thanks for sharing your repo and data, this is great. However I would l like to point out a major bug in evaluation, I was going through the test set of the Travel Planning task. I realized that their can be multiple valid solutions, and the evaluator only considers one solution as valid. 

To prove my point you can refer to trip_planning_example_1, here is the question:

You plan to visit 3 European cities for 15 days in total. You only take direct flights to commute between cities. You want to spend 6 days in Split. You want to spend 4 days in Manchester. You want to spend 7 days in Riga.\n\nHere are the cities that have direct flights:\nRiga and Manchester, from Manchester to Split.\n\nFind a trip plan of visiting the cities for 15 days by taking direct flights to commute between them.

Possible solution:
1. Golden Plan as per testset:
**Day 1-7:** Arriving in Riga and visit Riga for 7 days.
**Day 7:** Fly from Riga to Manchester.
**Day 7-10:** Visit Manchester for 4 days.
**Day 10:** Fly from Manchester to Split.
**Day 10-15:** Visit Split for 6 days.

and 

2. Alternate solution
**Day 1-6:** Arriving in Split and visit Split for 6 days.
**Day 6:** Fly from Split to Manchester.
**Day 6-9:** Visit Manchester for 4 days.
**Day 9:** Fly from Manchester to Riga.
**Day 9-15:** Visit Riga for 7 days.

both are valid given the problem description and constraints. As long as Manchester is visited second either solution will still hold valid.

**Comment by swarooprm** [comment]
Hi, there is no direct flight from Split to Manchester, as mentioned in the constrained ("from Manchester to Split"). So there is only one solution as provided in the golden solution. Alternate solution is not feasible.

Thank you for your question.
